services:
  app:
    build: .
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "80:80"

    # depends_on:
      # - mongo
      # - redis
    # environment:
      # - MONGO_URI=mongodb://mongo:27017/weather
      # - REDIS_URL=redis://redis:6379

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

  # redis:
  #   image: redis
  #   ports: 
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

# volumes:
  # mongo-data:
  # redis-data:

# version: '3.8'
# services:
#   backend:
#     build: .
#     ports:
#       - "4000:4000"
#     networks:
#       - app-network

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge